### ISSUE TITLE
Implement League Trades

### ISSUE THREAD

**Issue by cwendt94** [cwendt94/espn-api#1]
Need to figure out how trades can be accessed and viewed with ESPN's new v3 API endpoint.

**Comment by cwendt94** [comment]
I put in a feature suggestion to ESPN to add all trades of previous and current seasons. They responded saying they have gotten this request a lot and are in the process of adding it to their website!

So hopefully trade feature will be coming soon!

**Comment by jcordell** [comment]
Hi, any update on if/when trades would become available?  Very interested in this feature!

**Comment by cwendt94** [comment]
Yes, I hope to have it done by the end of the week!

**Comment by jcordell** [comment]
> Yes, I hope to have it done by the end of the week!

Best news I've heard all week!  If there's a patreon/donation box I'd be happy to donate to the cause

**Comment by jcordell** [comment]
Do you know if user auth is required for the trades endpoint or if all public leagues are viewable?

**Comment by cwendt94** [comment]
I am glad to hear! I do not have a donation box but maybe I will add one in the future!

I just checked a public league and I get a 401 error "not authorized", so it looks like user auth will be required to see any of the league activity.
