### ISSUE TITLE
ESPN Login/Authentication not working

### ISSUE THREAD

**Issue by davidjoshlee** [cwendt94/espn-api#100]
I've been unable to login to ESPN using my username/pw. (see attached for error message from the request)
<img width="1043" alt="Screen Shot 2020-08-29 at 3 53 11 PM" src="https://user-images.githubusercontent.com/26885498/91647454-c8a6b900-ea0f-11ea-991c-0c68a7f0f22f.png">

**Comment by davidjoshlee** [comment]
Here's my script: 
`from espn_api.requests import espn_requests`
`e = espn_requests.EspnFantasyRequests('nfl', 2019, LEAGUEID)`
`e.authentication(USERNAME, PASSWORD)`

**Comment by cwendt94** [comment]
I will have to look into this error. Do you have any extra security when logging into ESPN?

**Comment by davidjoshlee** [comment]
I do not. Thanks!

**Comment by cwendt94** [comment]
It's not working for me as well. I think ESPN updated their authentication endpoint. I did verify SWID and espn_s2 still work.

I'm going to look into how web and mobile login into fantasy.

**Comment by cwendt94** [comment]
I have been looking at how web authenticates and it looks like they are using google recaptcha for extra authentication. Here are the logs when I update using these endpoints
```python
url_api_key = 'https://registerdisney.go.com/jgc/v6/client/ESPN-ONESITE.WEB-PROD/api-key?langPref=en-US'
url_login = 'https://registerdisney.go.com/jgc/v6/client/ESPN-ONESITE.WEB-PROD/guest/login?langPref=en-US'
{'data': None, 'error': {'keyCategory': 'FAILURE_BY_DESIGN', 'conversationId': None, 'correlationId': '88778c0d-30bc-493f-a651-f3887f2ca1fa', 
'errors': [{'code': 'AUTHORIZATION_CREDENTIALS', 'category': 'FAILURE_BY_DESIGN', 'inputName': None, 'errorId': '1c328375-ad5b-4e02-b6ac-b02f94b15d50', 
'timestamp': '2020-09-09T19:21:55.675-0700', 
'data': {'type': 'GenericReasonCodeErrorData', 'reasonCode': 'PALOMINO_CHECK_FAILED'}, 'developerMessage': None, 'content': None}]}}
```

Im not sure what `'PALOMINO_CHECK_FAILED` means

On the web ESPN calls google API to get a key right before the login call. The call sequence looks like this
```
Get a API Key https://registerdisney.go.com/jgc/v6/client/ESPN-ONESITE.WEB-PROD/api-key?langPref=en-US
Get a recaptcha https://www.google.com/recaptcha/api2/reload?k=6LdIg6MZAAAAAFYsKbfC_YLPlx4DZ3U7IJMcOI67
Then login https://registerdisney.go.com/jgc/v6/client/ESPN-ONESITE.WEB-PROD/guest/login?langPref=en-US
```

I have also been trying to see which endpoint mobile authenticates too and see what authentication they are using. However they are now using https so I cannot see auth url path.

I would love some help if anyone has any ideas or experience with google recaptcha  API

**Comment by GTrabucco** [comment]
Hey I figured it out. When creating a new league object you need to pass in the swid and espn_2 param values. you can locate those values in your browsers cookies. then you need to add the cookie object to all your league_get requests. 

I've attached a screenshot of an example. Let me know if you're all able to get it

![Screen Shot 2020-09-24 at 2 39 42 PM](https://user-images.githubusercontent.com/8575410/94185864-e0892580-fe73-11ea-84b0-a3f33a31e912.png)

**Comment by cwendt94** [comment]
@GTrabucco thanks for posting, but this issue is for using`username` and `password`. Passing `swid` and `espn_2` parameters works and is already part of the package. You can see here https://github.com/cwendt94/espn-api/blob/master/espn_api/requests/espn_requests.py#L18 that every request passes cookies from when the League is created.

**Comment by cwendt94** [comment]
Discussions on trying to figure out the latest ESPN Login API is here #128

**Comment by kylewest520** [comment]
@GTrabucco I appreciate you taking a look! Please join @cwendt94 and I on the search for how to username and password working :)

**Comment by DesiPilla** [comment]
I was also struggling with this, but I believe I have found a work-around for it. I wrote a function [`get_credentials()`](https://github.com/DesiPilla/espn-api-v3/blob/d9b8e065d784c6f8f5ad7ec1f9511ed65387d30e/authorize.py#L10) that uses `Selenium` to open up a browser where a user can log in (the default chrome profile is used, which may log the user in automatically if they have used espn.com recently). The `swid` and `espn_s2` cookies are then fetched automatically and can be [stored for future use](https://github.com/DesiPilla/espn-api-v3/blob/d9b8e065d784c6f8f5ad7ec1f9511ed65387d30e/league.py#L42).

I hope this helps you. I'll leave it up to you on how/where would be best to integrate this into your repo, but this was how I tackled the issue. I've linked the corresponding code in my repo, but here it is for ease:

```
def get_credentials(user=None):
    '''
    This function identifies the SWID and ESPN_S2 for a user using Selenium.
    
    The function will identify the default Chrome profile for a user on the
    machine, and open up a browser using this account.
    
    The user will be prompted to sign in to their ESPN account if they are
    not auto-signed in by their browser.
    
    The swid and espn_s2 cookies are identified and returned.
    '''
    # Get list of users on computer
    users = os.listdir('C://Users')
    for i in ['All Users', 'Default', 'Default User', 'desktop.ini', 'Public']:
        users.remove(i)
    print("[FETCHING CREDENTIALS] All users: ", users)
    
    if user is None:
        # Select first user
        user = users[0]
        print("[FETCHING CREDENTIALS] Using user: {}".format(users[0]))
    
    # Locate and use the default Chrome profile for the user
    print("[FETCHING CREDENTIALS] Locating default Chrome profile...")
    options = webdriver.ChromeOptions() 
    options.add_argument(r'--user-data-dir=C:/Users/{}/AppData/Local/Google/Chrome/User Data'.format(user))
    options.add_argument('--profile-directory=Default')

    # Instantiate Chrome instance using Selenium and the default Chrome profile
    print("[FETCHING CREDENTIALS] Instantiating Chrome browser...")
    DRIVER_PATH = 'C://chromedriver.exe'
    try: 
        driver = webdriver.Chrome(executable_path=DRIVER_PATH, chrome_options=options)
    except InvalidArgumentException as e:
        if "user data directory is already in use" in str(e):
            #driver.close()  # Close window
            raise Exception("Chrome is already open in another window. Please close all other Chrome windows and re-launch.")
    
    # Navigate to ESPN website for league and login
    driver.get('https://fantasy.espn.com/')

    # Check if user is logged in automatically by browser
    cookies = [cookie["name"] for cookie in driver.get_cookies()] # Get list of cookie names
    if ("SWID" not in cookies) or ("espn_s2" not in cookies):
        # Wait for user to log in maunally
        print("[FETCHING CREDENTIALS] Login to ESPN account in browser.")
        driver.find_element_by_xpath('//*[@id="global-user-trigger"]').click()
        #driver.find_element_by_xpath('//*[@id="global-viewport"]/div[3]/div/ul[1]/li[7]/a').click()
        while True:
            time.sleep(5)
            cookies = [cookie["name"] for cookie in driver.get_cookies()] # Get updated list of cookie names
            if ("SWID" in cookies) and ("espn_s2" in cookies):
                print("[FETCHING CREDENTIALS] Login detected.")
                break;            
            print("[FETCHING CREDENTIALS] Login not detected... waiting 5 seconds...")
    else:
        print("[FETCHING CREDENTIALS] Login detected.")
        pass
           
    # Identify cookies for user
    swid, espn_s2 = None, None
    cookies = driver.get_cookies()
    for cookie in cookies:
        if cookie['name'] == 'SWID':
            swid = cookie['value'][1:-1]
        if cookie['name'] == 'espn_s2':
            espn_s2 = cookie['value']
    
    #return driver
    if swid is None:
        raise Exception("[FETCHING CREDENTIALS] ERROR: SWID cookie not found.")
    if espn_s2 is None:
        raise Exception("[FETCHING CREDENTIALS] ERROR: SWID cookie not found.")    
    
    # Close the browser        
    driver.close()
    
    print("[FETCHING CREDENTIALS] ESPN Credenitals:\n[FETCHING CREDENTIALS] ---------------------")
    print("[FETCHING CREDENTIALS] swid: {}\n[FETCHING CREDENTIALS] espn_s2: {}".format(swid, espn_s2))
    return swid, espn_s2

```

For storing credentials:
```
try:
    login = pd.read_csv('login.csv').iloc[:, 1:]   # Load cached credentials if file exists
except:
    login = pd.DataFrame(columns=['manager', 'league_name', 'league_id', 'swid', 'espn_s2'])
    creds = {'manager':self.teams[1].owner, 'league_name':self.settings['name'], 'league_id':self.league_id, 'swid':self.swid, 'espn_s2':self.espn_s2}
    login = login.append(creds, ignore_index=True)
    login.to_csv('login.csv', index=False) 
    print("[BUILDING LEAGUE] League credentials saved.")
```

**Comment by cwendt94** [comment]
Thanks @DesiPilla for this work around! It would be great if you could also post this in the [API Key Discussion](https://github.com/cwendt94/espn-api/discussions/128) and I can mark it as the answer! 

I'm thinking at this point to remove the username and password from this package. Using `Selenium` is smart work around and programmatically way to get a users `swid` and `espn_s2` but I think leaving it up to the caller to get their `swid` and `espn_s2` for private leagues is the best option.

**Comment by DesiPilla** [comment]
@cwendt94 I agree that it's much more streamlined to have the user be responsible for their `swid` and `espn_s2` credentials. In my repo, the end goal is to create an application that non-programmers can use (though I'm not sure I'll ever spend the time actually getting that far). However, the `selenium` solution is still quite ugly for that use case haha.

**Comment by cwendt94** [comment]
Yeah that makes sense for a application for non-programmers!

**Comment by kylewest520** [comment]
Sorry that I went dark on this but as soon as the regular season ended last year I moved on to other projects. Just now getting back into fantasy to prep for 2021 and I'm delighted to see @DesiPilla's contribution! Great work and thanks for sharing your approach. My application is similar to @DesiPilla where I want to target non-programmers. I've actually had decent success with asking users to provide their swid and espn_s2 credentials directly rather than try to get them programmatically. That probably has something to do with people feeling like the app is more "secure" if they are inputting the data themselves.

@cwendt94 @DesiPilla do either of you care to share how you're using the data? I'd be curious to check it out. Here's my use case: https://fantasyleaguegoat.com/

**Comment by DesiPilla** [comment]
Wow @kylewest520 that looks awesome! I am a Data Scientist by trade (but made most of my application before I knew anything about data science) and _not_ a programmer, so my use case is not nearly as pretty or useful. I have a very rudimentary kivy app that I use for myself and a few friends. I keep telling myself I'll one day make a nice easy-to-use GUI or webpage to host it, but I never seem to find the energy to actually build it out.

**Comment by kylewest520** [comment]
@DesiPilla I'm a data scientist too! I wanted to learn more about web programming which is why I built out the site in addition to the analysis. If you're interested in working together we could explore the idea of adding some of your app's analysis routines into my web page. After all, we are leveraging the same data. It would just be a matter of converting your analysis/logic that's currently in the kivy python app and re-writing in PHP to embed within my code. Could be fun! Let me know.

**Comment by cwendt94** [comment]
@kylewest520 That looks like a really awesome website! For my league I have created a private website/react native app where I host some league stats, blogs and custom rules (loser punishment, keeper rules, etc). I found that the ESPN website doesn't show past leagues that well and its not easy to see previous season winners, roster, and stats.
