### ISSUE TITLE
Get # of points scored by a certain player in a given week 

### ISSUE THREAD

**Issue by roshanverma2001** [cwendt94/espn-api#101]
Hi,

I want to be able to get the number of points scored by a player in a given week.

If a user inputs a name, i want to be able to find that player in the league and then return the # of points.

I've written a function to return a player based on an inputted name, but i'm not sure how to go about getting the # of points they've scored. I can't seem to access the attributes in the [Box Player Class](https://github.com/cwendt94/espn-api/wiki/Box-Player-Class)

The Wiki says you should be able to access that value from any player class however I think i'm doing something wrong as I am unable to access it that way.

<img width="1063" alt="Screen Shot 2020-09-01 at 12 07 02 AM" src="https://user-images.githubusercontent.com/18652212/91813158-1295c780-ebe7-11ea-8376-dc67fc31cfa4.png">

<img width="396" alt="Screen Shot 2020-09-01 at 12 07 19 AM" src="https://user-images.githubusercontent.com/18652212/91813174-1cb7c600-ebe7-11ea-980b-8276a2898f6b.png">

Any guidance on how to access the box player class would be appreciated!

**Comment by cwendt94** [comment]
From the error it looks like you are accessing the [Player Class](https://github.com/cwendt94/espn-api/wiki/Player-Class) which does not have points. That class is used to store general data for that player.

If you want to get a specific players points and information for a given week I think you have three options. 
1. If you know the player is on someones team you can use the `box_scores` function and then check each teams lineup ([Box Score Class](https://github.com/cwendt94/espn-api/wiki/Box-Score-Class)). This is not the best way of doing it but you don't have to add any new calls.

2. Looking at the data I believe when the Team classes are created we have all of the players information for each fantasy team. We could update the Player class to store week stats that have already been played. 

3. If the player is not on a fantasy team ESPN has a API to get a specific players data https://fantasy.espn.com/apis/v3/games/ffl/seasons/2019/segments/0/leagues/${league_id}?view=kona_playercard and can be filtered using `x-fantasy-filter` header filter. This information could be used to create a Player object from the second option and return the information.

I think I can add options 2 and 3 in the next couple days to the package.

**Comment by cwendt94** [comment]
Check out package v0.5.0 and the newest `player_info` function. Returns [Player Class](https://github.com/cwendt94/espn-api/wiki/Player-Class) with new `stats` field.
