### ISSUE TITLE
league.draft broken?

### ISSUE THREAD

**Issue by tkmerkel** [cwendt94/espn-api#102]
Hi there,

Been using this to construct a draft board for past years since espn doesn't do it. Was working yesterday and now it only shows where DeVante Adams was selected?

![image](https://user-images.githubusercontent.com/27387297/91917313-2bed5100-ec85-11ea-99a8-f659988122f6.png)

Thanks for the hard work btw, I love the package!

**Comment by cwendt94** [comment]
Thanks for reporting this! I am seeing the same issue on one of my leagues as well.

Looking into the API call it seems they do not return all players now by default and now have to add a header filter. I will push a new package shortly!

I'm glad you like the package! :)

**Comment by cwendt94** [comment]
Fix should be in the latest package v0.4.1! Let me know if you see any other issues!

**Comment by tkmerkel** [comment]
Awesome! Thank you so much!
