### ISSUE TITLE
name change?

### ISSUE THREAD

**Issue by joshbis** [cwendt94/espn-api#104]
Firing up my old scripts for a new season -- did this used to be called ff_espn_api?

**Comment by cwendt94** [comment]
Yes it was updated over the offseason! New import syntax and pip package

**Comment by joshbis** [comment]
Nice! I was stumped at why my old version wouldn't update. Glad the ESPN didn't break private leagues! I've already used this to do some graphical draft recaps.

**Comment by cwendt94** [comment]
I'm glad everything is working for you!
