### ISSUE TITLE
Unexpected Behavior: API Output Printing with Each Command

### ISSUE THREAD

**Issue by dkelly-proj** [cwendt94/espn-api#106]
This may be an issue with my settings or something locally, but this is behavior that I just started encountering today. Below is some simple code to build a dataframe of games throughout the regular season of my league. I would not expect any of these lines to generate output, but it seems like each iteration of the for loops cause the JSON response from the API to be printed. This occurs even when running from the command line.

If this isn't an issue with the package I'll close and look elsewhere. I appreciate any help!

![image](https://user-images.githubusercontent.com/38297815/92123455-aecbf400-edca-11ea-93e4-2e7d0a730c45.png)

**Comment by cwendt94** [comment]
It looks like you are running the package in debug mode. How are you initializing the league object? You want to make sure you assign each value in the constructor like
```python
league = League(league_id=1234, year=2020, swid='{123-456-789}', espn_s2='4657983486')
```

**Comment by dkelly-proj** [comment]
Yikes, yes I was passing debug = True for some reason when initializing the league object. Working just fine now that I removed that. Thanks for the assist.

**Comment by cwendt94** [comment]
Awesome, no problem!
