### ISSUE TITLE
league.recent_activity() for 2020

### ISSUE THREAD

**Issue by joshbis** [cwendt94/espn-api#109]
I'm not seeing any recent activity for this year. Has something changed on the ESPN side?

I.e., this:
`year = 2020
lg = League(league_id, year, espn_s2, swid)
lg.recent_activity()
`
returns: "[]"

There have been activities in our league post-draft; so I don't think that's the explanation.

**Comment by cwendt94** [comment]
Are you using the latest package version 0.5.0, I made a bug fix for recent activity.

**Comment by joshbis** [comment]
That did, in fact, fix it!
