### ISSUE TITLE
Recent activity for basketball

### ISSUE THREAD

**Issue by jwill24** [cwendt94/espn-api#112]
Hey, this API is awesome and it's really approved my fantasy football keeper league that's been together for 10 years. I also want to use it to get the recent activity for my fantasy basketball league. I noticed that the capability to access the activity is not in the basketball/league.py. Is this something that can be easily added? Or is it not possible? 

Thanks so much!

**Comment by cwendt94** [comment]
I'm glad it's been helpful! Yeah I think it should be pretty simple adding recent activity to basketball. I will look into it in the next couple days!

**Comment by jwill24** [comment]
I tried to implement it the same way as you do for football, but it is only giving me the team names. Not the adds and drops. 
Here is what I added:
https://github.com/jwill24/espn-api/blob/master/espn_api/basketball/constant.py#L102-L115
https://github.com/jwill24/espn-api/blob/master/espn_api/basketball/league.py#L70-L94

**Comment by cwendt94** [comment]
I see the issue. You need to add `self._fetch_players()` when the league is created. Look at https://github.com/cwendt94/espn-api/blob/master/espn_api/football/league.py#L27. This will get all NBA player id's and name

**Comment by cwendt94** [comment]
When you get a chance could you open a PR for the new `recent_activity` changes in basketball!
