### ISSUE TITLE
Get division names instead of only their IDs

### ISSUE THREAD

**Issue by gobo7793** [cwendt94/espn-api#116]
Can you can make that the division names are also accessable instead only their IDs using Team.division_id? Example: Team.division_name

If I want to list the current standings, I want output the division names using the API only, instead of mapping the IDs manually to their names.

What I have currently:
print(my_team.division_id) -> "0"

What I want, for example:
print(my_team.division_name) -> "West"

**Comment by cwendt94** [comment]
Yeah, that should be an easy update!

**Comment by cwendt94** [comment]
Included in the latest package v0.6.0
