### ISSUE TITLE
player_info function causing: 'IndexError: list index out of range'

### ISSUE THREAD

**Issue by mknox10** [cwendt94/espn-api#120]
After doing a little debugging I was able to determine that the issue is caused when using the player_info function to get the player class for Michael Thomas. As it turns out there are actually two Michael Thomas's in the NFL which is why I believe the issue is occuring.

The second Michael Thomas is a safety on the Texans:
[https://www.nfl.com/players/active/all?query=Michael%20Thomas](https://www.nfl.com/players/active/all?query=Michael%20Thomas)

The error that occurs for me is as following:

>   File "C:\...\draft_results.py", line 8, in run
>     player = espnleague.player_info(pick.playerName)
>   File "C:\...\espn_api\football\league.py", line 274, in player_info
>     player = data['players'][0]
> IndexError: list index out of range

Although the above stack trace is not super relevant as the issue is created in the fetch_players function inside of the 'base_league.py' file:

`    def _fetch_players(self):
        data = self.espn_request.get_pro_players()
        # Map all player id's to player name
        for player in data:
            # two way map to find playerId's by name
            self.player_map[player['id']] = player['fullName']
            self.player_map[player['fullName']] = player['id']`

As you can see once the loop gets to the second Michael Thomas the id stored under the existing 'Michael Thomas' key gets overridden with the id for the second Michael Thomas.

Not sure what would be the best approach to fix this? I was able to get it working if I changed player_info function to use the playerId instead of the playerName. Although that is not optimal as getting the player using their name is much easier.

Love the espn-api! Keep up the great work, it is much appreciated.

**Comment by cwendt94** [comment]
Oh wow I didn't think about that happening! Thanks for reporting this! I will have to think about it and see if I can come up with a solution.

In the meantime I will update documentation to say name or playerId for player_info function

**Comment by mknox10** [comment]
I should have specified more, but I did have to change the code inside the actual player_function to get it to work. So currently using the id does not work.

**Comment by cwendt94** [comment]
Got it, I will update to allow playerId. Thanks!
