### ISSUE TITLE
[Football API][Feature Request] Injury status

### ISSUE THREAD

**Issue by joshbis** [cwendt94/espn-api#122]
Sorry if this is already somewhere, but is there a part of the player class that identifies whether a player is questionable, doubtful, or out?

**Comment by cwendt94** [comment]
That's a great request! I thought the player class had injury status but it's only for basketball. I will make the update later today!

**Comment by cwendt94** [comment]
I also added a `injured` boolean field that will be a quick way to know if the player is injured
