### ISSUE TITLE
Free_Agent & POSITION_MAP missing positions

### ISSUE THREAD

**Issue by rysull23** [cwendt94/espn-api#127]
Hi there. Happy 2020. Two things: 

1. The `free_agents` method only takes position as a str.
2. The `POSITION_MAP` constant doesn't have certain positions on the left side of the dict.

Hence, if you try to pass something like `free_agents(position = 'LB')`, you get a genericized response consisting of any and all positions. Also, you can't pass `free_agents(position=10)` because this violates the method definition.

Last year, I updated my local copy of `POSITION_MAP` as follows. Now I'm not using my local copy and was wondering if you could make the respective update? I'm sure there's a more official way to do what I'm trying to do, but wanted to share what worked for me. Thanks so much!

```
POSITION_MAP = {
    0: 'QB',
    1: 'TQB',
    2: 'RB',
    3: 'RB/WR',
    4: 'WR',
    5: 'WR/TE',
    6: 'TE',
    7: 'OP',
    8: 'DT',
    9: 'DE',
    10: 'LB',
    11: 'DL',
    12: 'CB',
    13: 'S',
    14: 'DB',
    15: 'DP',
    16: 'D/ST',
    17: 'K',
    18: 'P',
    19: 'HC',
    20: 'BE',
    21: 'IR',
    22: '',
    23: 'RB/WR/TE',
    24: 'ER',
    25: 'Rookie',
    'QB': 0,
    'RB': 2,
    'WR': 4,
    'TE': 6,
    'D/ST': 16,
    'K': 17,
    'FLEX': 23,
    'DT': 8,
    'DE': 9,
    'LB': 10,
    'DL': 11,
    'CB': 12,
    'S': 13,
    'DB': 14,
    'DP': 15
}
```

**Comment by cwendt94** [comment]
Thanks for reporting this! I will add the updated position map and allow for position id. I should be able to get to it tomorrow!

**Comment by rysull23** [comment]
Welcome! Thank you. Also, curious, is this the accurate import I should be making? I noticed you may have renamed it this year?

`from ff_espn_api import League`

**Comment by cwendt94** [comment]
This package now has a new name and import syntax. You will want to install the latest version

'pip install espn_api'
'from espn_api.football import League'

**Comment by rysull23** [comment]
Very cool. Making big progress! Nice work.

I just tried hitting `free_agents(position='K')` and throwing an error. I'm hitting the `free_agent` api for many positions and only getting the error for 'K'

```
fa = l.free_agents(position = 'K')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/xxx/Documents/Development/ff-project/venv/lib/python3.7/site-packages/espn_api/football/league.py", line 260, in free_agents
    return [BoxPlayer(player, pro_schedule, positional_rankings, week) for player in players]
  File "/Users/xxx/Documents/Development/ff-project/venv/lib/python3.7/site-packages/espn_api/football/league.py", line 260, in <listcomp>
    return [BoxPlayer(player, pro_schedule, positional_rankings, week) for player in players]
  File "/Users/xxx/Documents/Development/ff-project/venv/lib/python3.7/site-packages/espn_api/football/box_player.py", line 8, in __init__
    super(BoxPlayer, self).__init__(data)
  File "/Users/xxx/Documents/Development/ff-project/venv/lib/python3.7/site-packages/espn_api/football/player.py", line 28, in __init__
    for stats in player_stats:
TypeError: 'NoneType' object is not iterable
```

**Comment by cwendt94** [comment]
Interesting, I'm looking into the error now!

**Comment by cwendt94** [comment]
Fixed that issue and everything should be good in package version `0.7.1`

**Comment by rysull23** [comment]
Updated the package and it's working. That was quick! Thanks! If only the day job had such quick turnarounds...

**Comment by cwendt94** [comment]
No problem! Haha I know what you mean!
