### ISSUE TITLE
How to get total points scored by player

### ISSUE THREAD

**Issue by glennrfriedman** [cwendt94/espn-api#134]
Hi, 

First off, this library is incredible; I've been trying to do something with my league data for years but have always been blocked. 

I'm trying to do an analysis to compare our draft to total points scored to figure out which have been the best/worst players drafted so far using a metric of points per dollar. 

In order to do this I've constructed the draft by team to a dataframe and am pulling all active player data into another, however, the stats dict is rather difficult to work with. Is there a way anyone knows of to get total points scored by player? 

Let me know; thank you!

**Comment by glennrfriedman** [comment]
`player_list = []
for i in range(len(team_rosters)):
	roster = team_rosters[i]
	for x in range(len(roster)):
		# print(roster[x].name)
		player_dict = {
					'name': roster[x].name,
					'playerId': roster[x].playerId,
					'posRank': roster[x].posRank,
					'eligibleSlots': roster[x].eligibleSlots,
					'acquisitionType': roster[x].acquisitionType,
					'proTeam': roster[x].proTeam,
					'position': roster[x].position,
					'injuryStatus': roster[x].injuryStatus,
					'injured': roster[x].injured,
					'stats': roster[x].player_stats
		}
		player_list.append(player_dict)
		# print(roster[x].stats)

players_df = pd.DataFrame(player_list)
print(players_df['stats'][4])`

**Comment by cwendt94** [comment]
Thanks for creating an issue for this. Here is a discussion on the `stats` field and a little more break down of the dict #131. I think it would make sense to add two new fields for the Player class (`total_points` and `projected_total_points`) to make it a little easier to access.

**Comment by glennrfriedman** [comment]
Thank you! Definitely agree if those were added that would be pretty great.
