### ISSUE TITLE
Issue with BoxPlayer class

### ISSUE THREAD

**Issue by glennrfriedman** [cwendt94/espn-api#139]
Hi @cwendt94, 

Attempting to dive deeper into the BoxPlayer class and continuing to receive the following error

```
espn_api/football/player.py", line 10, in <listcomp>
    self.eligibleSlots = [POSITION_MAP[pos] for pos in json_parsing(data, 'eligibleSlots')]
KeyError: 'RB/WR'
```

the code I'm using to call the class is as follows; no issues with the League or Player classes

```
pro_schedule = league._get_pro_schedule(week)
positional_rankings = league._get_positional_ratings(week)
player = team_list[11]['roster'][5].__dict__
box_player = BoxPlayer(player, pro_schedule, positional_rankings, week, year)
```

Where week = 4 and year = 2020; I've also tried week = 3 thinking that may have something to do with it but it did not. 

team_list is a list made up of all the teams in the league from league.teams

Also have attempted the player with and without the .__dict__ dict conversion. When I don't use .__dict__ I get the following error

```
/espn_api/football/player.py", line 12, in __init__
    self.proTeam = PRO_TEAM_MAP[json_parsing(data, 'proTeamId')]
TypeError: unhashable type: 'list'
```

I was really just trying to following the example of calling BoxPlayer from the league.py sheet here in the free_agents function so not sure what I'm doing wrong here. Please let me know if this is a code issue or I'm just wildly missing the boat; thank you!

```
players = data['players']
pro_schedule = self._get_pro_schedule(week)
positional_rankings = self._get_positional_ratings(week)

return [BoxPlayer(player, pro_schedule, positional_rankings, week, self.year) for player in players]
```

The weird thing is I know that when I run league.free_agents() I get no error so maybe I'm just passing the wrong player data into the BoxPlayer but I'm not sure.

**Comment by cwendt94** [comment]
Hey @glennrfriedman,
So the reason why you can't create a Box Player is the `player` data passed is actually a large dict object from ESPN's API and you are trying to pass the Player Class data as that dict object.
This code
```python
players = data['players']
pro_schedule = self._get_pro_schedule(week)
positional_rankings = self._get_positional_ratings(week)

return [BoxPlayer(player, pro_schedule, positional_rankings, week, self.year) for player in players]
```
`players = data['players']` Is from ESPN's API and is a different structured dict than than `league.teams[0].roster[0].__dict__`

What data are you trying to get by creating a Box Player?

**Comment by glennrfriedman** [comment]
Got it; I'm trying to get the data for the prior week for the player - both the project and actual points scored to calculate the variance and determine biggest boom/bust players for the week. Would also need the slot to figure out who was a starter and who was benched. 

Its part of a project I'm working on using Dash/Plotly to build a web dashboard leveraging this API.

**Comment by cwendt94** [comment]
I think for that use case you will have to use `box_scores` call to know if the player was benched or starting on the teams roster.
``` python
box_scores = league.box_scores(league.current_week - 1)
```
After getting the previous week [box scores](https://github.com/cwendt94/espn-api/wiki/Box-Score-Class) you then can compare those [box players](https://github.com/cwendt94/espn-api/wiki/Box-Player-Class) information to a current teams player projected points.
