### ISSUE TITLE
Football - Issue with box_scores

### ISSUE THREAD

**Issue by bebey-james** [cwendt94/espn-api#140]
I'm seeing "IndexError: list index out of range" when calling box_scores

```
>>> league.box_scores()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.7/site-packages/espn_api/football/league.py", line 200, in box_scores
    pro_schedule = self._get_pro_schedule(week)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/espn_api/base_league.py", line 84, in _get_pro_schedule
    game_data = team['proGamesByScoringPeriod'][str(scoringPeriodId)][0]
IndexError: list index out of range
```

Looks like this is due to how espn is handling data for covid-related schedule changes. When a game gets rescheduled, the scoringPeriod list is empty for that week which is what is causing the indexError. For example, here's the section of the API response for New England whose week 5 game got rescheduled:

```
{'abbrev': 'NE', 'byeWeek': 0, 'id': 17, 'location': 'New England', 'name': 'Patriots', 'proGamesByScoringPeriod': 
            {'1': [
                {'awayProTeamId': 15, 'date': 1600016400000, 'homeProTeamId': 17, 'id': 401220131, 'scoringPeriodId': 1, 'startTimeTBD': False, 'statsOfficial': True, 'validForLocking': True
                } ],
            ...
            ...
            ...
            ...
            '5': [], 
```

Adding a condition to check for an empty list on line 86 of base_league.py seems to fix the issue:
```if team['id'] != 0 and (str(scoringPeriodId) in team['proGamesByScoringPeriod'].keys() and team['proGamesByScoringPeriod'][str(scoringPeriodId)]):```

Tested this locally and will submit a PR in a bit. @cwendt94, please let me know if you think this will work without breaking anything else.

**Comment by cwendt94** [comment]
@bebey-james Thanks for investigating and creating a PR! I will get in merged in and create a release

**Comment by cwendt94** [comment]
The fix is now in v0.8.1!

**Comment by bebey-james** [comment]
@cwendt94 Happy to help. Thanks for the quick response!

**Comment by sambailey54** [comment]
How do we go about pushing the latest version of the code to our bot?

**Comment by cwendt94** [comment]
@sambailey54 https://github.com/dtcarls/fantasy_football_chat_bot repo will have to update to the latest package v0.8.1. It looks like there is already a issue for it dtcarls/fantasy_football_chat_bot#78
