### ISSUE TITLE
2018 & 2019 seasons were played, but API returns they did not exist

### ISSUE THREAD

**Issue by iWHOswald** [cwendt94/espn-api#146]
I was playing around with this API to find which years existed for a given league using the following function:

```
    def year_finder(self):
        year_array = []
        for i in range(2013,2021):
            try:
                league = League(league_id=self.league_id.get(), year=i) #pull league ID from a tkinter entry; iterate thru years to find those that exist
                year_array.append(i)
            except:
                print(str(i) + "League did not exist. skipping.")
        print(year_array)
```
However it is returning that the 2018 and 2019 seasons did not exist. I tried hardcoding the league info but it again says that the league doesn't exist. Has anyone else had this issue? They were definitely played (my league has existed since 2013). These are the only two years that cannot be found.

**Comment by cwendt94** [comment]
That is strange, I have not seen an issue like that before. During those two seasons was the league private?

**Comment by iWHOswald** [comment]
Ah yes that is the case. Thanks for the help.
