### ISSUE TITLE
Recent Activity now blocked without authentication?

### ISSUE THREAD

**Issue by dtcarls** [cwendt94/espn-api#148]
Trying to retrieve recent activity of a league now returns a 401 code even with a public league. I do not have a private league to test if I authentication with SWID etc if it will properly return league activity.

To test (using 0.8.2)
`from espn_api.football import League`
#public league id
`league = League(164483, 2020)`
`league.recent_activity(msg_type='FA')`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "espn_api-0.8.2-py3.8.egg/espn_api/football/league.py", line 161, in recent_activity
  File "espn_api-0.8.2-py3.8.egg/espn_api/requests/espn_requests.py", line 39, in league_get
  File "espn_api-0.8.2-py3.8.egg/espn_api/requests/espn_requests.py", line 10, in checkRequestStatus
Exception: Access Denied
`league.standings()`
[Team(PAIN TRAIN), Team(Jake from State Farm), Team(Mightnt i the Grissle), Team(Adam's Hairy  Meatstick), Team(Road to the Offseason), Team(KEWPS BAG O DICKS), Team(Coop's SM Fantasy), Team(Draft Bot  おねえちゃん), Team(Person Woman Man Kamara TD), Team(She likes me for me-mes)]
`league.recent_activity(msg_type='WAIVER')`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "espn_api-0.8.2-py3.8.egg/espn_api/football/league.py", line 161, in recent_activity
  File "espn_api-0.8.2-py3.8.egg/espn_api/requests/espn_requests.py", line 39, in league_get
  File "espn_api-0.8.2-py3.8.egg/espn_api/requests/espn_requests.py", line 10, in checkRequestStatus
Exception: Access Denied

Additionally accessing from the webpage url and weatching network logs you can see the same.
https://fantasy.espn.com/football/recentactivity?leagueId=164483
shows an empty activity page.
401 on this call 
https://fantasy.espn.com/apis/v3/games/ffl/seasons/2020/segments/0/leagues/164483/communication/?view=kona_league_communication

Can validate the league is public by visiting https://fantasy.espn.com/football/league?leagueId=164483
Weirdly, going to that page doesn't display the configured LM note either.

I don't think there is anything that can be done to the package, but may want to add some documentation to recent activity noting the requirement of the SWID (once validated).

Additionally, I am doing this while games are on going so it may all just resolve itself without active games occuring, unknown.

**Comment by cwendt94** [comment]
Thanks for letting me know! I will keep an eye on it and hopefully it will fix itself.

**Comment by cwendt94** [comment]
@dtcarls I thought I remember seeing this issue before. I found, I mentioned it in the Wiki but just on the home page https://github.com/cwendt94/espn-api/wiki under `Getting Started`. I will add better documentation so that it is clear for recent activity.
