### ISSUE TITLE
[Basketball API] Free Agents

### ISSUE THREAD

**Issue by Ferra18** [cwendt94/espn-api#152]
Hi,
I used this fantastic API a year ago to perform some analysis on my fantasy baskeball league. On December 20th I'll have my draft for this season and I wanted to use again the analysis that I did for 2020 season. I updated the package, but now I cannot find the method that gets the free agent players of the league. Is this a mistake (I saw that an important refactor has been done) or the functionality is not working anymore for the fantasy basketball (I also saw that in fantasy football there is this feature)?

**Comment by cwendt94** [comment]
Hey @Ferra18, I do not believe basketball ever had the free agent functionality to it. However I just did a quick implementation using most of the logic from Football and it shouldn't be a problem adding it to basketball! I can update the package with the feature in the next day or two!

**Comment by Ferra18** [comment]
Fantastic mate! Really appreciated! If my work leaves me some time I'll consider to contribute to the API in the next months 🥳

**Comment by cwendt94** [comment]
That would be awesome! The Basketball API could use some love 😄

**Comment by cwendt94** [comment]
Free Agent is now in package version 0.9.0!
