### ISSUE TITLE
Running into trouble authenticating, seems to be tripping a 401 error

### ISSUE THREAD

**Issue by randerson1** [cwendt94/espn-api#164]
Trying to use this (wonderful!) API for the first time. I was able to pull my league's data once, then I tried to rewrite my code to read from a json I provided. After that, I started getting Access Denied requests. At first, I guessed it was something to do with being ratelimited, but now I'm not so sure.

Error being thrown:
`Traceback (most recent call last):
  File "main.py", line 5, in <module>
    league = League(data["league_id"], data["year"])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ff_espn_api/league.py", line 60, in __init__
    self._fetch_league()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ff_espn_api/league.py", line 70, in _fetch_league
    checkRequestStatus(self.status)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ff_espn_api/league.py", line 24, in checkRequestStatus
    raise Exception("Access Denied")
Exception: Access Denied
 `

Code I attempted: 
`from ff_espn_api import League
import json
with open("espn_creds.json", "r") as read_file:
  data = json.load(read_file)
league = League(data["league_id"], data["year"])
print(league)`

**Comment by Dumie101** [comment]
You need to use swid and espn_s2 for authentication. This will be found under developer tools, application, cookies. 
League(data["league_id"], data["year"], swid, espn_s2)

**Comment by randerson1** [comment]
Thanks for the reply! Unfortunately, got the same thing when running with my swid and espn_s2:

`from ff_espn_api import League
import json
with open("espn_creds.json", "r") as read_file:
  data = json.load(read_file)
league = League(data["league_id"], data["year"], data["swid"], data["espn_s2"])
print(league)`

`Traceback (most recent call last):
  File "main.py", line 5, in <module>
    league = League(data["league_id"], data["year"], data["swid"], data["espn_s2"])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ff_espn_api/league.py", line 60, in __init__
    self._fetch_league()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ff_espn_api/league.py", line 70, in _fetch_league
    checkRequestStatus(self.status)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ff_espn_api/league.py", line 24, in checkRequestStatus
    raise Exception("Access Denied")
Exception: Access Denied`

**Comment by randerson1** [comment]
Interestingly, looks like my espn_s2 just changed when I went to check my league on the FF website. I entered that new s2 and still got the same error.

**Comment by Dumie101** [comment]
i made a mistake first time, try passing in espn_s2 before the swid

**Comment by Dumie101** [comment]
def __init__(self, league_id: int, year: int, espn_s2=None, swid=None, username=None, password=None, debug=False): 

^ that is the method header expect you don't need to pass in your username and password

**Comment by randerson1** [comment]
That worked!! Thanks

**Comment by cwendt94** [comment]
Thanks @Dumie101 for helping with this! I try not to move any of the init vars around but just in case its always good practice to write out the variable names you are using in the init call like this
```python3
league = League(league_id=222, year=2019,  swid='{1234}', espn_s2='123456')
```
This way the order does not matter when initializing the league!
