### ISSUE TITLE
Error when retrieving a league drafted after the start of the season

### ISSUE THREAD

**Issue by json-h** [cwendt94/espn-api#165]
Currently using the basketball API. I only have access to one (test) league at the moment, which was started after the NBA season started. 

In line 35 in matchups.py:

`if 'cumulativeScore' in data['home'].keys():`

This returns true, but in line 43:

`'result': data['home']['cumulativeScore']['scoreByStat'][i]['result']} for i in data['home']['cumulativeScore']['scoreByStat'].keys()`

`data['home']['cumulativeScore']['scoreByStat']` will be a NoneType with no attribute `keys()`, I think because unplayed weeks will contain incomplete data. I actually fixed this by changing line 35 to 

`if 'cumulativeScore' in data['home'].keys() and data['home']['cumulativeScore']['scoreByStat']:`

and it works now, but there might be a better way to do it.

**Comment by cwendt94** [comment]
Thanks @json-h for reporting this! I will look into this error and try to have a fix in the next couple days!

**Comment by cwendt94** [comment]
Your solution looks good! The fix will be in package version 0.9.4!
