### ISSUE TITLE
NBA players in roster have wrong injury status

### ISSUE THREAD

**Issue by mjyousif** [cwendt94/espn-api#178]
The injury status seems to be wrong for players in the roster. One of my players is out, yet his injury status returns the same as others. Additionally, the injury status returns 'NORMAL' if they are on the roster, whereas free agents never have this status. Free agents also have their actual injury status marked.
![image](https://user-images.githubusercontent.com/33187058/105624998-b2006480-5deb-11eb-8f69-eee6e8293b39.png)
![image](https://user-images.githubusercontent.com/33187058/105624975-854c4d00-5deb-11eb-9945-138ded5ed836.png)

**Comment by cwendt94** [comment]
Thanks for reporting this bug! This was happening in the football League as well, should be an easy fix!

**Comment by cwendt94** [comment]
Fix is in v0.11.1!
