### ISSUE TITLE
Relative Import

### ISSUE THREAD

**Issue by chrismjim** [cwendt94/espn-api#203]
Hi, I am attempting to use the API within Colab but am having trouble. 

Whenever it gets to: 
"from ..base_league import BaseLeague"

I receive this error message: 

"ImportError                               Traceback (most recent call last)
<ipython-input-4-2699921125e2> in <module>()
      7 import pdb
      8 
----> 9 from ..base_league import BaseLeague
     10 from .team import Team
     11 from .player import Player

ImportError: attempted relative import with no known parent package"

Can anyone offer any help? 

Any response is greatly appreciated! 

<img width="1314" alt="Screen Shot 2021-04-27 at 4 34 58 PM" src="https://user-images.githubusercontent.com/31938984/116325362-d49d7300-a776-11eb-83a2-f118a296b548.png">
<img width="1328" alt="Screen Shot 2021-04-27 at 4 35 11 PM" src="https://user-images.githubusercontent.com/31938984/116325380-dcf5ae00-a776-11eb-98cd-8c189ed670ff.png">

**Comment by cwendt94** [comment]
How are you using the package in Colab? I was able to run this command and not run into any errors
```
!pip install espn_api
from espn_api.baseball import League
```

**Comment by chrismjim** [comment]
I'm an idiot. I ran the above code (yours) in a new colab window and it works fine. Thank you for the prompt response cwendt94!

**Comment by cwendt94** [comment]
No worries, glad it is working!
