### ISSUE TITLE
error on installing espn_api during numpy installation

### ISSUE THREAD

**Issue by JunkyardCat** [cwendt94/espn-api#204]
so when i install espn_api using pip install espn_api it errors out when it is installing numpy. is there a specific python version i should use? im currently using python 3.8.9

**Comment by cwendt94** [comment]
What does the error say? Any python version past 3.6 should work and the package makes sure the correct numpy version package is installed.

**Comment by JunkyardCat** [comment]
@cwendt94 
please see attach for the error
[error.txt](https://github.com/cwendt94/espn-api/files/6403300/error.txt)

**Comment by cwendt94** [comment]
Hmm how are you installing the package and do you already have a numpy version installed on your machine?

**Comment by JunkyardCat** [comment]
@cwendt94 
i am using venv so there's no packages installed.
pip install espn_api. thats it

**Comment by JunkyardCat** [comment]
@cwendt94 
in addition to what i said above you can replicate the issue. I use python 3.8.9/3.9.4 then create venv then install numpy 1.17.0

**Comment by cwendt94** [comment]
Thanks for looking into this and being able to repeat it! 

That's strange numpy 1.17.0 is not working with python 3.8.9 when it says Require Python >= 3.5

It looks like other people have had the same problem and there was a bug with 1.17.0 for python 3.8. Version 1.17.5 should fix this issue.
