### ISSUE TITLE
error when using the free_agents module

### ISSUE THREAD

**Issue by JunkyardCat** [cwendt94/espn-api#207]
### Sport

Football

### Summary

espn_api version 0.15.0

when i use the free_agent function it gives me error
code that i used
```league.free_agents(size=5)```
error:
```KeyError: 'proGamesByScoringPeriod'```

**Comment by cwendt94** [comment]
Thanks for reporting this! I will see if I can recreate this error on my side.

**Comment by cwendt94** [comment]
What year is the league initialized with, 2021?

**Comment by cwendt94** [comment]
This should be fixed in v0.15.1
