### ISSUE TITLE
Adding projected scores to scraping

### ISSUE THREAD

**Issue by spkane31** [cwendt94/espn-api#213]
### Sport

Football

### Summary

Is it possible to add the projected scores to the matchup class? This would be a great addition, I'd be happy to add this functionality if you point me to a few places.

**Comment by dtcarls** [comment]
box_scores -> home/away_lineup -> boxplayer -> projected_points

**Comment by cwendt94** [comment]
The matchup class is really meant to be used for older season leagues before 2019 to get matchup outcomes. For current season and leagues after 2018 the `box_scores` interface and [class](https://github.com/cwendt94/espn-api/wiki/Box-Score-Class) has more in depth information and also projected points.

If you are viewing the box_score on the current week it will have the `home_projected` and `away_projected` fields populated. If you are looking at older seaons/weeks, it will have to be calculated using the boxplayer projected_points as @dtcarls mentioned.
