### ISSUE TITLE
Can't get score for a single scoring period in the last week of the league

### ISSUE THREAD

**Issue by mjyousif** [cwendt94/espn-api#215]
### Sport

Basketball

### Summary

I cannot get the daily score for games played in the last week of my league, being the last week of the regular season. Using the box_scores method, I can pass in a number for scoring_period and get the scores for that day for any day except the games played in the last week, for which each day will return the total score.

```
x = league.box_scores(scoring_period=139, matchup_total=False)
x[0].home_score
```
With 139 being the last day of the 2nd to last week, this returns the correct score for that team on that day, 168
```
x = league.box_scores(scoring_period=140, matchup_total=False)
x[0].home_score
```
With 140  being the first day of the last week, this returns the incorrect score of 1410, being that teams score for the whole week. The same is true for any other scoring_period in the last week.

**Comment by cwendt94** [comment]
Thanks for reporting this! I see the same thing in my league, looking into it now

**Comment by cwendt94** [comment]
This is now fixed in v0.16.0

**Comment by mjyousif** [comment]
Does this need to be applied to away as well?
https://github.com/cwendt94/espn-api/blob/master/espn_api/basketball/box_score.py#L26

**Comment by cwendt94** [comment]
Great catch! That code should be grouped together as it is common between home and away.
