### ISSUE TITLE
Username/Password Authentication Issue

### ISSUE THREAD

**Issue by dshane8** [cwendt94/espn-api#218]
### Sport

Football

### Summary

I'm trying to get started using the API, but when I try to initialize a private league with a username and password I keep getting `Authentication unsuccessful - check username and password input`. I'm able to manually sign in using the same credentials on the ESPN site, so I'm sure I have my username and password correct. I've even tried creating a whole new account and am still getting this error. I've also tried using my email instead of the username and keep getting the same result. Any help on this issue would be greatly appreciated.

**Comment by cwendt94** [comment]
ESPN updated their authentication a little while ago which broke using username and password through their API. Its going to be removed from the package. To authenticate a private league you will have to use your SWID and ESPN_S2 credentials. Check out this discussion for getting those values https://github.com/cwendt94/espn-api/discussions/150

**Comment by dshane8** [comment]
Thanks for getting back to me! I appreciate the response and your work on the API. So unfortunately what you're saying is there is no way to authenticate via Username & Password anymore?

**Comment by cwendt94** [comment]
Correct, here is a thread with some more details https://github.com/cwendt94/espn-api/discussions/128#discussioncomment-144327. Luckily once you get your SWID and ESPN_S2 credentials they don't seem to change and can then be used every time for the library.
