### ISSUE TITLE
Filtering free agents not working

### ISSUE THREAD

**Issue by erik-h** [cwendt94/espn-api#249]
### Sport

Hockey

### Summary

I was trying to filter `League.free_agents` to only display goaltenders, however it looks like the free agent filtering isn't working for me at all. No matter what I put for the `position` I always get the same unfiltered results.

**Comment by cwendt94** [comment]
Hi @erik-h, thanks for pointing this out. The position map only haves the mapping from `position_id` to name and not `position` to id. I will add a fix but you can try this for goalies
```
league.free_agents(position_id=5)
```

**Comment by cwendt94** [comment]
This is fixed in v0.18.2!

**Comment by erik-h** [comment]
Awesome, thanks again!
