### ISSUE TITLE
Add playoff % to standings and/or team class

### ISSUE THREAD

**Issue by dtcarls** [cwendt94/espn-api#256]
### Sport

Football

### Summary

On the standings page, there is now a predicted percentage to make the playoffs. I would like to access this in the Team class or whatever you feel is appropriate.

**Comment by dtcarls** [comment]
https://fantasy.espn.com/apis/v3/games/FFL/seasons/2021/segments/0/leagues/{LEAGUE_ID_HERE}/?view=mStandings
stored in `playoffPct`

**Comment by cwendt94** [comment]
Thanks, I was just looking at that. I see ESPN now provides `draftDayProjectedRank` and `currentProjectedRank` that could be good team information.

**Comment by dtcarls** [comment]
There are also some interesting projections from a simulation in there, like projected wins and losses
```
"currentSimulationResults": {
        "divisionWinPct": 0.0,
        "modeRecord": {
            "gamesBack": 0.0,
            "losses": 11,
            "percentage": 0.0,
            "pointsAgainst": 0.0,
            "pointsFor": 0.0,
            "streakLength": 0,
            "streakType": "NONE",
            "ties": 0,
            "wins": 3
        },
        "playoffPct": 0.019,
        "rank": 10
    },
```
