### ISSUE TITLE
Get historical projections (and other data)

### ISSUE THREAD

**Issue by DesiPilla** [cwendt94/espn-api#279]
### Sport

Football

### Summary

The `box_score` class is built to get box score data from any week. However, projection data is only available for live matchups. For matchups that have already ended, the value '-1' is returned. Can we add the ability to get the initial projection (sum of every starting player's projected point total for that week) for historical weeks?

Also, the `home_team` and `away_team` points to the current state of those objects, and so its attributes (# wins/losses/ties, standing, points for, etc.) is not accessible using this class. Can these objects be altered to whatever state they would have been in during that week? (i.e., if I pull the box scores from Week 7 of 2018, the `Team` object would be as if had been pulled during that week & year)

I'm looking to do some analysis and this would make the data scraping much easier.

**Comment by cwendt94** [comment]
I should definitely be able to add total projected points for historical weeks.

I will have to look into getting team data for that current week. I think it is possible but will need to change the API call to get the team data and then create new Team objects for the box scores

**Comment by mtdickey** [comment]
I would be interested in this feature too.

**Comment by cwendt94** [comment]
You should be able to get projected scores for previous leagues in the box_scores class now. It doesn't have to be the current match up. However you still can't get this data for any years before 2019 because of ESPN removing that data.

**Comment by mtdickey** [comment]
In version 0.22.1, I'm still seeing the `box.home_projected` and `box.away_projected` attributes are `-1` for past weeks.

The only way I've found to get the total projected for past weeks is by summing across the `projected_points` attribute of the `BoxPlayer` classes in each lineup.  Is there another way?

**Comment by dtcarls** [comment]
I'm seeing the same behavior as @mtdickey while pulling data from week 3.

**Comment by dtcarls** [comment]
Looks like it's set to -1 by default "if the week is over/not set" 
https://github.com/cwendt94/espn-api/blob/1dda8f4c162fb80c1027987b1a5018b33db41cb6/espn_api/football/box_score.py#L10
