### ISSUE TITLE
league.free_agents() returns exactly 50 results

### ISSUE THREAD

**Issue by ConduciveMocha** [cwendt94/espn-api#285]
### Sport

Basketball

### Summary

Getting free agents only returns the first 50 results for me. It looks like this is a cookie error as it returns the same result as querying  'https://fantasy.espn.com/apis/v3/games/fba/seasons/2022/players?scoringPeriodId=0&view=players_wl' in an incognito tab. 

It seems like 'ESPN API Request: url: https://fantasy.espn.com/apis/v3/games/fba/seasons/2022/players params: {'view': 'players_wl'} headers: {'x-fantasy-filter': '{"filterActive": {"value": true}}'} ' returns all players and free_agents() can be derived by crosschecking the player list with the active rosters. Let  me know if you have any insights or if you want me to implement free_agents() by cross checking current rosters.

**Comment by dtcarls** [comment]
I think you can set a `limit` header parameter also. Similar to this gist I put together to grab ADP.
https://gist.github.com/dtcarls/c6158cd8ad41e0941571807052098a0f

**Comment by cwendt94** [comment]
Hi @ConduciveMocha that's the default size `free_agents` function is set for. You can adjust it by setting the size you want like
```python3
league.free_agents(size=100)
```
Check out the [Basketball Wiki](https://github.com/cwendt94/espn-api/wiki/League-Class-Basketball#functions) which shows the different variables you can pass to the free agent function.
