### ISSUE TITLE
Replace the home/away in the outcomes[str]  list with a 'W'/ 'L'

### ISSUE THREAD

**Issue by RagaPribadi** [cwendt94/espn-api#304]
### Sport

Football

### Summary

The outcomes list in the Teams class contains a list of winners, but only by the 'Home' and 'Away' designation. However, I don't have any info on who's the away and home team unless I access the boxscore class. The issue with accessing the boxscore class is that I'm not able index it by team.   

Would it be possible to replace the home/away in the outcomes[str]  list with a 'W'/ 'L'?

**Comment by cwendt94** [comment]
I think that makes sense and shouldn't be hard to update!

**Comment by cwendt94** [comment]
should be fixed in package v0.19.1
