### ISSUE TITLE
Add transactionCounter data to Team

### ISSUE THREAD

**Issue by ButteredGroove** [cwendt94/espn-api#335]
Please add team `data['transactionCounter']` information to the `Team` object for the football api.

There are several interesting data points therein which would be nice to access via the API.

**Comment by ButteredGroove** [comment]
Yup!  You could add something like this to the Team `__init__`:
```
        self.acquisitions = data['transactionCounter']['acquisitions']
        self.move_to_ir = data['transactionCounter']['moveToIR']
        self.trades = data['transactionCounter']['trades']
```

**Comment by cwendt94** [comment]
Added variables are now in v0.19.4 The new vars are
```python
acquisitions 
acquisition_budget_spent 
drops 
trades 
```
