### ISSUE TITLE
Way to Tell If Matchup is a Playoff/Championship Matchup

### ISSUE THREAD

**Issue by joeyagreco** [cwendt94/espn-api#337]
### Sport

Football

### Summary

Currently, there is no clear way to tell if a matchup is a regular season, playoff, or championship matchup.

Using `League.settings.reg_season_count` (and a little logic), you can determine if a week is a playoff week.

However, for a matchup, there is no way of determining if it is a playoff matchup or a matchup that is happening during a playoff week that is just "for fun".

The same goes for determining if a matchup is a championship matchup.

Adding something to each team (similar to  the `Team.outcomes` list) that represents what type of matchup that week held for that team would be very helpful.

Example:

`Team.matchup_type`: 

```
[
"REG",
"REG",
"REG",
"REG",
"REG",
"REG",
"REG",
"REG",
"REG",
"REG",
"REG",
"REG",
"PLAY",
"PLAY",
"CHAMP"
]
```

**Comment by cwendt94** [comment]
new fields has been added to matchup and box score class
``` python3
is_playoff: bool
matchup_type: str # values NONE (regular game) WINNERS_BRACKET LOSERS_CONSOLATION_LADDER WINNERS_CONSOLATION_LADDER
```
