### ISSUE TITLE
Player.stats dict doesn't seem to include week 1 points/points breakdown

### ISSUE THREAD

**Issue by axing7** [cwendt94/espn-api#369]
`###` Sport

Football

### Summary

Player.stats dict doesn't include week 1, only weeks 2 and 3. Tried with both Davante Adams and Travis Kelce. Both players have played all 3 weeks, but only have 0: 2: and 3: keys in their stats dict. 

The steps I took to get the player object were:
```
league.load_roster_week(3)
teams = league.teams
teams[0].roster[0].stats
```
When I take out the load_roster_week() call, I only get season projected scores (0) and the last week (3).

This is my output when printing Adams' stats dict - circled the 0/2/3 for clarity. 
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/11250012/192589172-80565cf3-10cc-4753-a8d2-2bfe545be411.png">

I may be using this wrong - let me know if I am!

**Comment by cwendt94** [comment]
If you want the stats for that specific week you can use `box_scores` function. The load roster and base teams roster class will have just the total points for that player and the last two weeks of play.

Also if you are looking for just one player or a couple players stats you can use the `player_info` function.
