### ISSUE TITLE
ESPN basketball league initialization fails to find start date for 2023

### ISSUE THREAD

**Issue by joseulisesmena** [cwendt94/espn-api#373]
### Sport

Basketball

### Summary

My overall use case right now is that I want to be able to pull down projections for the 2023 season in order to perform pre-draft value over replacement player calculations. I can't do this with the package as-is because my 2023 season league fails to initialize.

Steps to replicate as follows. This code does not run successfully:
`from espn_api.basketball import League
league = League(league_id=8675309, year=2023, espn_s2='foo', swid='bar')`
I get an error that reads:
`min() arg is an empty sequence`
I do not get this error if I run it for 2022.
I traced this back to line 31 of league.py:
`self.start_date = datetime.datetime.fromtimestamp(min([i[1][1]/1000 for i in self._get_pro_schedule(1).items()])).date()`
I'm inferring that get_pro_schedule is returning an empty sequence, although I have not verified that. I can initialize a league object and return a player list if I comment out the above line and hard-code the start_date to the actual start of the NBA season, which I looked up online.

I don't know if this can be fixed or only documented as a limitation. I did not go deeper into get_pro_schedule to determine exactly what the cause of this is.

Thank you for your hard work on this! I've used this package for a few years and it's extremely useful.

**Comment by cwendt94** [comment]
Looks like you were correct, the `_get_pro_schedule` response was empty. `start_date` was not used anywhere so removing for now.
