### ISSUE TITLE
Basketball: League object creation failing for 2023 season

### ISSUE THREAD

**Issue by JamesPHawk** [cwendt94/espn-api#388]
### Sport

Basketball

### Summary

Not creating League object for 2023 season. Updated espn_api version to 0.25.0, verified my espn_s2 and swid, and I get archived data from the last season back, but changing the year to 2023 causes the League request to error out. 
`League(league_id=league_id, year=year, espn_s2=espn_s2, swid=swid, debug=False)`

### Logs/Data

`Traceback (most recent call last):
  File "C:\Users\pjhaw\PycharmProjects\TZDStats\stats\tzdstats.py", line 22, in <module>
    league = League(league_id=league_id, year=year, espn_s2=espn_s2, swid=swid)
  File "C:\Users\pjhaw\AppData\Local\Programs\Python\Python39\lib\site-packages\espn_api\basketball\league.py", line 22, in __init__
    data = self._fetch_league()
  File "C:\Users\pjhaw\AppData\Local\Programs\Python\Python39\lib\site-packages\espn_api\basketball\league.py", line 27, in _fetch_league
    self.start_date = datetime.datetime.fromtimestamp(min([i[1][1]/1000 for i in self._get_pro_schedule(1).items()])).date()
ValueError: min() arg is an empty sequence`

**Comment by monsdar** [comment]
Getting 2023 basketball data works for me, tested today. I was working with `.recent_activity` and `.scoreboard`, haven't used the rest yet.

**Comment by JamesPHawk** [comment]
That's really weird. I reset my s2 token as well and still no dice. What does your call to League look like?

**Comment by monsdar** [comment]
I just tried this small example, working as expected:

```
def main():
    league = League(league_id=LEAGUE_ID, year=LEAGUE_YEAR, espn_s2=ESPN_S2, swid=SWID)
    scores = league.box_scores(scoring_period=0)
    for score in scores:
        for player in score.home_lineup:
            pprint(player)
```

The league is set to public, no special settings I can think of...

**Comment by JamesPHawk** [comment]
Mine is set to private, but that wasn't an issue in the past. And I can still get data from the 2022 season.

**Comment by JamesPHawk** [comment]
Just verified that this also didn't work with a public league either...

**Comment by cwendt94** [comment]
Hey @JamesPHawk are you sure you have updated to latest version, in the error message is references `start_date` which was removed in this [commit](https://github.com/cwendt94/espn-api/commit/95a89acac6d7afff35b52110b6dea5359334caa8)

**Comment by JamesPHawk** [comment]
Ahhh great catch. I did an uninstall/reinstall, and pip freeze says espn_api is 0.25.0, but my league.py file is old for some reason.

**Comment by JamesPHawk** [comment]
Had to go into the league.py file and copy/paste the newest version, what's the better way to update it in the future? I thought pip3 uninstall/install would fix it but it did not.

**Comment by cwendt94** [comment]
I wonder if it was using your local version over the package installed. You can also do `pip install espn_api upgrade`. Also make sure to pull down the latest code if you are playing around locally.
