### ISSUE TITLE
Player Class not returning current year season stats

### ISSUE THREAD

**Issue by justinbt21** [cwendt94/espn-api#397]
### Sport

Basketball

### Summary

The current available stats to pull from the player class do not include the entire season stats for the current year - only the last 30, last 15, and last 7

Do you know if this is intended for now? (IE Haven't been able to find dict that stores info)

Attached screenshot for reference. Let me know if you need anything else to troubleshoot!

Thanks in advance. Love the work you've put into this!

<img width="614" alt="Screen Shot 2022-11-08 at 12 19 16 AM" src="https://user-images.githubusercontent.com/14880324/200512152-db12e294-9c01-4a53-a916-c834ca072463.png">

**Comment by cwendt94** [comment]
Thanks for reporting this! This is the same issue as this discussion #396 and is a bug! This recently broke with some player class stats update! Fixing now and will be in package v0.26.2

**Comment by justinbt21** [comment]
Awesome -- thank you for the quick turnaround. Appreciate all the work!
