### ISSUE TITLE
Incorrect names for tiebreaker settings

### ISSUE THREAD

**Issue by DesiPilla** [cwendt94/espn-api#399]
### Sport

Football

### Summary

In my fantasy football league, ties for playoff seedings are settled by a team's total `points for`. There are no tiebreakers for regular season matchups.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/44902815/200659335-8250aed8-2b5e-444c-8e1d-abb890071bfd.png">

However, I noticed that `league.settings.playoff_seed_tie_rule` returned `NONE` for my team. This is not correct. I assume that this field is intended to contain that setting, as the ESPN UI displays the setting as "Playoff Seeding Tie Breaker".

Unless I am misinterpreting the intent of this setting, I believe this needs to be corrected.

**Comment by DesiPilla** [comment]
It appears that `data['scheduleSettings']['playoffSeedingRule']` contains the information behind playoff seeding tiebreakers. `data['scoringSettings']['playoffMatchupTieRule']` would seem to be the playoff-version of `data['scoringSettings']['matchupTieRule']`. I'm not sure exactly what it means for `playoffMatchupTieRule` to be `NONE` (as it is in the case of my league), since one of the two teams must advance, but this is nevertheless distinct from tiebreakers for playoff seeding.

**Comment by DesiPilla** [comment]
Proposed [pull request](https://github.com/cwendt94/espn-api/pull/400) to make this change.

**Comment by cwendt94** [comment]
Thanks for catching this and creating a PR!
