### ISSUE TITLE
appliedStatsTotal returns incorrect team_score when score is changed by commissioner

### ISSUE THREAD

**Issue by bberk** [cwendt94/espn-api#403]
### Sport

Football

### Summary

When the commissioner manually changes the score of a team, the previous score is returned by the BoxScore class.
[box_score.py#L39](https://github.com/cwendt94/espn-api/blob/d4b7c97f05252ca28346cd9cdd26fb63d6761f36/espn_api/football/box_score.py#L39) should be updated to be `team_score =data[team]['totalPoints']`

### Logs/Data

The value being used to populate team_score: `data[team]['rosterForCurrentScoringPeriod']['appliedStatTotal'] = 195.15999999999997`
The field with the correct value: 
data[team]['totalPoints'] = 203.26

**Comment by cwendt94** [comment]
Thanks for reporting this bug, I will check it out!
