### ISSUE TITLE
Matchup projections

### ISSUE THREAD

**Issue by rbta-svg** [cwendt94/espn-api#410]
### Sport

Basketball

### Summary

Hi there,

I have built a bot for the ESPN Fantasy basketball with the goal to provide a bunch of useful functions like trade analysis and team rankings by projections.
I am now trying to add a function to use on Mondays, that generate an expectation score for the player in the given week.
For example, if Trae Young plays 4 times in the specific week and is averaging 50 points, the expectation would be that he totals around 200 points for that week. This helps with regards to deciding if a player should be moved from the bench or not.

For this reason, I wanted to suggest the addition of the player schedule in a given matchup.

That being said, thank you cdwendt94 and contributors for this amazing repo!

**Comment by galkatz7** [comment]
https://github.com/cwendt94/espn-api/issues/289#issuecomment-984226198

**Comment by rbta-svg** [comment]
> #289 (comment)

Thank you, I was able to build the feature I was looking for!
