### ISSUE TITLE
Pip install method deprecation warning

### ISSUE THREAD

**Issue by dtcarls** [cwendt94/espn-api#426]
### Sport

Football

### Summary

When installing the latest version with pip there is this warning.

`DEPRECATION: espn_api is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559`

**Comment by cwendt94** [comment]
Thanks for reporting this. I will look into fixing this after the holidays
