### ISSUE TITLE
Having trouble finding playoff data for H2H Fantasy Basketball league

### ISSUE THREAD

**Issue by coolbrett** [cwendt94/espn-api#427]
Hey guys! Love using this API.

I'm trying to retrieve playoff matchups for previous seasons for my H2H fantasy basketball league. I've tried using the week number that I think is associated with the week that a playoff matchup happened

Like say, we had a 18 week regular season and the playoffs were in weeks 19 and 20. I'm using `league.scoreboard()` and passing in a playoff week but I'm getting a KeyError.

**Comment by cwendt94** [comment]
Try using the `box_scores` functionality and passing in the `matchup_period`.  On the [wiki](https://github.com/cwendt94/espn-api/wiki/League-Class-Basketball) it explains the different fields you can pass in.
