### ISSUE TITLE
KeyError: 'location' in Fantasy BBall H2H Categories

### ISSUE THREAD

**Issue by JamesPHawk** [cwendt94/espn-api#495]
### Sport

Basketball

### Summary

Trying to make a basic connection to my private H2H categories league with this
```python
league = League(league_id=league_id, year=year, espn_s2=espn_s2, swid=swid, debug=False)
``` 
Getting this error block at runtime
```python
Traceback (most recent call last):
  File "my file", line 21, in <module>
    league = League(league_id=league_id, year=year, espn_s2=espn_s2, swid=swid, debug=False)
  File "\espn_api\basketball\league.py", line 25, in __init__
    self.fetch_league()
  File "\espn_api\basketball\league.py", line 29, in fetch_league
    self._fetch_teams(data)
  File "\espn_api\basketball\league.py", line 51, in _fetch_teams
    super()._fetch_teams(data, TeamClass=Team)
  File "\espn_api\base_league.py", line 65, in _fetch_teams
    self.teams.append(TeamClass(team, roster=roster, member=member, schedule=schedule, year=seasonId))
  File "\espn_api\basketball\team.py", line 11, in __init__
    self.team_name = "%s %s" % (data['location'], data['nickname'])
KeyError: 'location'

``` 

Some other threads have been raised in different sports, not sure what I could be missing but it's been a minute since I've used this API so I could be missing something.

**Comment by goose-36** [comment]
I am getting the same for my H2H NHL league. 

`File ~/Library/CloudStorage/GoogleDrive-pulmonarygoose@gmail.com/My Drive/Hockey Analytics/Programs/espnfantasy/league.py:39, in setup_league(year)
     33 def setup_league(year):
     34     """
     35     Create the initial datasets using ESPN Fantasy API. 
     36 
     37     Save dataframes to pickle files to reduce number of calls on ESPN Fantasy API. 
     38     """
---> 39     league = League(cf.league_id, year, cf.espn_s2, cf.swid);
     40     teams = league.teams;    
     41     no_weeks = len(teams[0].schedule);

File ~/anaconda3/lib/python3.11/site-packages/espn_api/hockey/league.py:21, in League.__init__(self, league_id, year, espn_s2, swid, fetch_league, debug)
     18 super().__init__(league_id=league_id, year=year, sport='nhl', espn_s2=espn_s2, swid=swid, debug=debug)
     20 if fetch_league:
---> 21     self.fetch_league()

File ~/anaconda3/lib/python3.11/site-packages/espn_api/hockey/league.py:25, in League.fetch_league(self)
     23 def fetch_league(self):
     24     data = self._fetch_league()
---> 25     self._fetch_teams(data)

File ~/anaconda3/lib/python3.11/site-packages/espn_api/hockey/league.py:47, in League._fetch_teams(self, data)
     45 def _fetch_teams(self, data):
     46     '''Fetch teams in league'''
---> 47     super()._fetch_teams(data, TeamClass=Team)
     49     # replace opponentIds in schedule with team instances
     50     for team in self.teams:

File ~/anaconda3/lib/python3.11/site-packages/espn_api/base_league.py:64, in BaseLeague._fetch_teams(self, data, TeamClass, pro_schedule)
     62             break
     63     roster = team_roster[team['id']]
---> 64     self.teams.append(TeamClass(team, roster=roster, member=member, schedule=schedule, year=seasonId, pro_schedule=pro_schedule))
     66 # sort by team ID
     67 self.teams = sorted(self.teams, key=lambda x: x.team_id, reverse=False)

File ~/anaconda3/lib/python3.11/site-packages/espn_api/hockey/team.py:12, in Team.__init__(self, data, member, roster, schedule, year, **kwargs)
     10 self.team_id = data['id']
     11 self.team_abbrev = data['abbrev']
---> 12 self.team_name = "%s %s" % (data['location'], data['nickname'])
     13 self.division_id = data['divisionId']
     14 self.division_name = ''  # set by caller

KeyError: 'location'`

**Comment by goose-36** [comment]
@JamesPHawk @cwendt94  I think I found the issue. ESPN has amalgamated the "location" and "nickname" fields in your team settings and just has "name" now. 

I edited the code in team.py (Line 12) to reflect this:
self.team_name = "%s" % (data['name'])

It seems to work correctly without throwing the error.

**Comment by goose-36** [comment]
@JamesPHawk this issue has been rectified already. Check the closed issues. I fell victim of not reading the closed issues as well...

**Comment by cwendt94** [comment]
Make sure to update to the latest version v0.33.0, that has the fix for this.
