### ISSUE TITLE
League.previousSeasons no longer an attribute? 

### ISSUE THREAD

**Issue by Jfreundlich01** [cwendt94/espn-api#522]
### Sport

Football

### Summary

Two days ago, League.previousSeasons was working perfectly. It returned a string, with a list of years in it. 

I am now getting 

`AttributeError: 'League' object has no attribute 'previousSeasons'`

When I loop through the list of attributes on the League object, previousSeason used to be after power_rankings and before recent_activity. Its now gone. 

Wondering if other folks have noticed this change! Thanks!

**Comment by cwendt94** [comment]
Strange, that code has not changed and is set in the [base_league.py](https://github.com/cwendt94/espn-api/blob/master/espn_api/base_league.py#L37)

**Comment by Jfreundlich01** [comment]
Welp, don't mind me. Was not in my virtual environment, so was using a previous version of the library. It is working as expected in

**Comment by Jfreundlich01** [comment]
Welp, don't mind me. Was not in my virtual environment, so was using a previous version of the library. It is working as expected in 0.34.0
