### ISSUE TITLE
League object fails to instantiate when not all teams of league have managers

### ISSUE THREAD

**Issue by tylerastraub** [cwendt94/espn-api#534]
### Sport

Basketball

### Summary

We had a member of our league drop all his players during playoffs so I removed his access to the league by removing his email from the league members page. When I went to run our power rankings program this morning, it suddenly stopped working. Adding in a dummy email for the team got everything to run smoothly again. If this is intended, then please close this, but I'm not sure why every team needs to have a team owner for the API to work. See attached image below for the error:

### Logs/Data

![image](https://github.com/cwendt94/espn-api/assets/43757504/0a829134-b3eb-4d92-9d29-44ea1b6913b0)

**Comment by cwendt94** [comment]
That is a bug, thanks for reporting. The get and default to single object in array was suppose to prevent that but I am guessing the `owners` field is present just an empty array. I will look into fixing this.
