### ISSUE TITLE
Unable to pull data from league

### ISSUE THREAD

**Issue by bobmarleydied** [cwendt94/espn-api#542]
### Sport

Baseball

### Summary

My code suddenly stopped being able to pull data from the league.  I tracked it down to requiring a different FANTASY_BASE_ENDPOINT.   If I change it from 'https://fantasy.espn.com/apis/v3/games/' to 'https://lm-api-reads.fantasy.espn.com/apis/v3/games/' then I'm able to pull data as normal.

**Comment by cwendt94** [comment]
Thanks for reporting, this was recently fixed in the latest package v0.36.0
