### ISSUE TITLE
Ties incorrectly assigned as outcomes

### ISSUE THREAD

**Issue by DesiPilla** [cwendt94/espn-api#566]
### Sport

Football

### Summary

When populating the `Team.outcomes` attribute, the logic only considers three outcomes: Undecided (games that haven't been completed yet), Win, and Loss.
```python
def _get_winner(self, winner: str, is_away: bool) -> str:
    if winner == "UNDECIDED":
        return "U"
    elif (is_away and winner == "AWAY") or (not is_away and winner == "HOME"):
        return "W"
    else:
        return "L"
```
Though ties are very rare (and even further, ties in a league that doesn't use tiebreakers), they happen. I just noticed in a league of mine from 2021, this value was wrong. In the event of a tie, both teams are given losses according to this logic.

A snapshot of what the data metadata looks like in events of a tie:
```python
{'away': {'cumulativeScore': {'losses': 0,
   'scoreByStat': { ... },
   'statBySlot': None,
   'ties': 0,
   'wins': 0},
  'gamesPlayed': 0,
  'pointsByScoringPeriod': {'8': 108.82},
  'teamId': 1,
  'totalPoints': 108.82},
 'home': {'cumulativeScore': {'losses': 0,
   'scoreByStat': {...},
  'totalPoints': 108.82},
 'id': 29,
 'matchupPeriodId': 8,
 'winner': 'TIE'}
```

**Comment by cwendt94** [comment]
Thanks for fixing!!
