### ISSUE TITLE
scoreboard and playoffs

### ISSUE THREAD

**Issue by joshbis** [cwendt94/espn-api#57]
Any idea if ESPN numbers the playoff weeks differently in league.scoreboard? I was trying to download all of our league's scores and a few years appear to have gaps in the sequence of weeks (e.g., pulling the matchups works for 1-12, 13-15 in 2015). 

I don't remember there being bye weeks scheduled, but I'm wondering if something in the first round of playoffs is treated differently.

**Comment by cwendt94** [comment]
For playoffs scoring can get a little tricky. Some leagues have playoffs where each team plays a team for two weeks or more than the normal one week. If that is the case the scoreboard functionality might not work properly.

This is where the fields scoringPeriod and MatchupPeriod that ESPN API provides differs. I think there needs to be logic checking these fields during the playoffs if a team has multiple scoringPeriods for one matchupPeriod.
