### ISSUE TITLE
Can't run league for hockey for 2025. Error in line 35, in __init__     if split['stats']:

### ISSUE THREAD

**Issue by jwinik** [cwendt94/espn-api#589]
### Sport

Hockey

### Summary

Picking this back up now that week 1 of hockey is done and got the following error when running League for 2025. Works fine for 2024. Seems like its an issue with the Player class in player.py

Thanks in advance for the help. Have used this for 4 years, really appreciate all the work that goes into maintaining this. 

### Logs/Data

`league = League(league_id = league_id, year = 2025, espn_s2 = espn_s2, swid = swid)`

>   File "...\anaconda3\lib\site-packages\espn_api\hockey\player.py", line 35, in __init__
>     if split['stats']:

**Comment by cwendt94** [comment]
I will check this out, thanks for reporting!

**Comment by cwendt94** [comment]
Fixed in v0.40.0!

**Comment by jwinik** [comment]
Amazing, thank you for doing this so quickly!
