### ISSUE TITLE
Feature request: Access to Live Draft

### ISSUE THREAD

**Issue by greatdansby** [cwendt94/espn-api#7]
The draft end-point currently implemented works for completed drafts, but not a live view. Would be great to view/participate in drafts via API.

**Comment by cwendt94** [comment]
Hi @greatdansby thank you for putting in a request! The live view of a draft would be cool. I would have to see how ESPN shows that data and what API endpoint they use.

For the participate feature that could be a little tricky. So far this package just pulls data from a current league. I have not tried posting/updating league data from the API.

I will try to look into it and see if these features are possible!

**Comment by cwendt94** [comment]
After some investigation I have not found a way to grab live draft data. When you draft, espn opens a new window for drafting and as far as I can tell, it is not calling the API. I haven't found a endpoint you can call to get the live data. I do not know if there is a way.

**Comment by cwendt94** [comment]
Closing, not possible at the moment
