### ISSUE TITLE
Recent Activity improvements

### ISSUE THREAD

**Issue by mlandrum22** [cwendt94/espn-api#71]
Our league differentiates (for keeper purposes) whether someone picks someone up via Waivers vs. via Free agency.

Would it be possible to add the difference when looking at recent activity?

Similar to only seeing trades, can there be a setting to only see "added" or "added by waivers"?

And finally, we are moving to FAAB next year (and would like to tie keeper values to FAAB spent), would it be possible to add in the monetary value of the waiver addition?

Thanks for an awesome API!

**Comment by cwendt94** [comment]
1st Question: Yes, I believe ESPN differentiates Waivers/Free Agency and I can add that to Recent Activity filter.

2nd Question: I am not very familiar with FAAB but I believe we can add the monetary value for successful wavier additions. However if you want all of the bids that were place even if they failed that data is located via another endpoint. Check out this PR  https://github.com/cwendt94/ff-espn-api/pull/59 for more info.

**Comment by mlandrum22** [comment]
Ohh that’s awesome news! Yeah I would only need successful bids.

**Comment by cwendt94** [comment]
Perfect. I will try to create a PR in the beginning of next week

**Comment by joshbis** [comment]
While you're at it, is it easy-ish to grab the dates of the transactions? I was curious to get time trends in trades, etc.

**Comment by mlandrum22** [comment]
Oh, that would be a sweet add. We were thinking about tying keeper value to when they were picked up.

**Comment by cwendt94** [comment]
Yeah adding the dates should be really simple

**Comment by cwendt94** [comment]
Because I am not in a FAAB I am not able to see what field would be added for the bid in recent activity. If I could see a sample from someone in a FAAB league I can add the field.

I am almost done with filter and date for recent activity

**Comment by joshbis** [comment]
Were dates ever added into recent activity?

**Comment by cwendt94** [comment]
Yes the dates have been added to recent activity

**Comment by joshbis** [comment]
awesome, must've been a version behind! thanks again.

**Comment by cwendt94** [comment]
No problem, and the wiki is up to date with the change!

**Comment by joshbis** [comment]
so the date is stored separately from the activity tuple?

**Comment by cwendt94** [comment]
Yeah, one date per activity

**Comment by joshbis** [comment]
cool - I just don't see it returned by:
`league.recent_activity(1)`

**Comment by cwendt94** [comment]
It was not added to the __repr__ so it won’t show. You can always check https://github.com/cwendt94/ff-espn-api/wiki for what variables are returned and in each class

**Comment by joshbis** [comment]
ok - I don't see how it gets returned, but I am almost certainly missing something obvious.

**Comment by cwendt94** [comment]
So you should be able to do league.recent_activity(1).date

**Comment by joshbis** [comment]
hmm, when I do that I get: 
```
league.recent_activity(1).date
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-1a439487e0b0> in <module>
----> 1 league.recent_activity(1).date

AttributeError: 'list' object has no attribute 'date'
```

**Comment by cwendt94** [comment]
Sorry meant to say league.recent_activity()[0].date because it returns a list of activities and each activity has a date

**Comment by joshbis** [comment]
got it!

**Comment by cwendt94** [comment]
You can now get bid_amount for wavier adds in the Recent Activity call. This is in v0.10.0
