### ISSUE TITLE
Weekly Roster?

### ISSUE THREAD

**Issue by joshbis** [cwendt94/espn-api#72]
Is there a way to get rosters by week? I don't see this on the ESPN site, so I'm not especially hopeful. 

Context is trying to calculate how many points on each team's roster came from draft, trade, and waiver pickups. I can probably reconstruct this from draft and activity, but it's nice that roster has it stored there already.

**Comment by cwendt94** [comment]
box_score function has week input which should have the information

**Comment by joshbis** [comment]
Oh, that would be ideal. But when I just looked at
```
box_scores = league.box_scores(week=1)
box_scores[1].away_lineup[4].acquisitionType

```
The result is "None" for all players.

**Comment by cwendt94** [comment]
Darn, let me look into that. I will have to check if that’s on my side or ESPN api side. But there def is a way to get previous week data!

**Comment by cwendt94** [comment]
As of right now the only time I see acquisitionType set in ESPN API data is getting the current roster. Trying box_score or roster endpoint with the scoringPeriod set in the past, ESPN sets acquisitionType to null

**Comment by joshbis** [comment]
ah, that's too bad. I started grabbing rosters at week 4. I guess I can manually reconstruct acquisition type for earlier weeks, it'll just be a mild hassle.
