### ISSUE TITLE
How do you use this with your website?

### ISSUE THREAD

**Issue by bduckley** [cwendt94/espn-api#79]
Not sure if it's appropriate to post this as an issue, but I was curious what you use for your league's website (you mention that you use this codebase for your own website), and/or how you use this codebase? I have been playing around with Django, but I'm not entirely sure of the best way to use this repo effectively with Django. I'm also a novice :)

**Comment by cwendt94** [comment]
Sure, I can give you a overview of what I do for my league website. I use Django as the backend framework. Everyone in my league has an account so when they log in it has a profile of their team with their name, position, PF, PA, and icon. On the home page I have the current week power rankings, standings and scoreboard. The site also host the league blog and rules. I also use this package to grab all of the leagues previous season stats and display teams average position, PF, PA, win loss ration compared to everyone else through out all the seasons they played.
