### ISSUE TITLE
Breakdown of Points

### ISSUE THREAD

**Issue by kevintpeters** [cwendt94/espn-api#80]
Right now I don't see anyting more than Points for a player.boxscore. Is it possible to see from the ESPN api what the breakdown was for that player (yards, kicks, tds)?

**Comment by cwendt94** [comment]
That’s a good question. I think you can, I will have to look at the data returned. ESPN API does not name their variables and values very well.

**Comment by kevintpeters** [comment]
Yea just something I think could be interesting. Thanks for responding
during the holiday. Let me know I can help looking into anything in the
off-season.

**Comment by cwendt94** [comment]
I agree and no problem! Thanks @kevintpeters , I am definitely going to try to add some of these features during the off-season!
