### ISSUE TITLE
Can't get matchup data from the championship round

### ISSUE THREAD

**Issue by bwalters13** [cwendt94/espn-api#83]
I am able to access the championship matchup with the scoreboard function but cannot view the lineups

**Comment by cwendt94** [comment]
If you are using the `scoreboard` function that will not have the lineups. To see the lineups you will want to use `box_scores` function. You can find out more information on the `box_scores` function and data [here on the wiki](https://github.com/cwendt94/ff-espn-api/wiki/Box-Score-Class)!

**Comment by bwalters13** [comment]
sorry should have been more clear.  when using the box_scores function it will only pull up through our semi final round.  i get a key error when trying league.box_scores(14)

**Comment by cwendt94** [comment]
Gotcha, that might be related to #78. Is your championship over two weeks? Also if you could run it in debug mode and attach the output that would be great!
