### ISSUE TITLE
League.current_week incorrect into playoffs

### ISSUE THREAD

**Issue by dtcarls** [cwendt94/espn-api#85]
League.current_week incorrect into playoffs.

`
>>> from ff_espn_api import League
>>> league = League(164483,2019)
>>> league.current_week
14
>>> league.nfl_week
18
`

**Comment by cwendt94** [comment]
The current_week is the matchup period so if the same teams play each other across multiple weeks, current_week will not align with nfl_week.

However now thinking about this, during playoffs some teams might have different matchup periods than other teams in the league. I will try to work on this during the off season to fix some of the bugs during playoffs.
