### ISSUE TITLE
Unable to get projected points for 2020 Season

### ISSUE THREAD

**Issue by scotttravel2005** [cwendt94/espn-api#93]
I may be missing something regarding working with the 2020 season, but it seems as though there is not box_score information for the week 1 upcoming season 2020.  I looked through the JSON views according to other posts and did not see a projected score per player, but on the app/site there are definitely projections for week 1, 2020.  Is there another way to get the pre-season projections?

Looking to compare ESPN's player projections with other sites leading up to 2020.

**Comment by cwendt94** [comment]
Hmm if your league has already drafted you should be able to get week 1 box scores. What is returned when calling `box_scores()`?

**Comment by scotttravel2005** [comment]
Here is the league (public):

https://fantasy.espn.com/apis/v3/games/ffl/seasons/2020/segments/0/leagues/63281490?view=mMatchup&view=mMatchScore

**Comment by cwendt94** [comment]
Awesome, thanks for the information! It looks like before the season starts NFL team's defenses do not have ranks against positions yet (which makes sense). I should have the fix soon!

**Comment by cwendt94** [comment]
This is fixed in the newest package version 0.3.2
