### ISSUE TITLE
Relative import

### ISSUE THREAD

**Issue by lordofthevale** [cwendt94/espn-api#96]
Hi,

Apologies if this is super basic but I downloaded the package and attempted to run all of the files but each one I get a "ImportError: attempted relative import with no known parent package".  Is there an edit I need to make to the overall file structure or to each file individually to get this to run properly?

Thank you!
Josh

**Comment by cwendt94** [comment]
Hey so you shouldn't have to do anything special for imports to work. How did you download the package from pip or the repo?

**Comment by lordofthevale** [comment]
Hi Christian - Thanks for getting back to me so quickly.  I installed w/ Git and it seemed to install fine and I ran the nosetests.
It may be that it is much simpler... I may not even be starting off in the right place (and again sorry if this is too basic - thought I knew enough python to run the program but maybe not).
- I've tried executing all of the files through Terminal (e.g. python3 activity.py, etc.) but I get relative import error with this (not sure if this is even the correct starting point)
- I tried the "from espn_api.football import League" command but seem to get another sort of issue


Jennifers-MacBook-Pro-2:football jasciarra$ **python3 activity.py**
Traceback (most recent call last):
  File "activity.py", line 1, in <module>
    from .constant import ACTIVITY_MAP
**ImportError: attempted relative import with no known parent package**

Jennifers-MacBook-Pro-2:espn-api jasciarra$ **python3 espn_api.football import League**
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: can't open file 'espn_api.football': **[Errno 2] No such file or directory**

Jennifers-MacBook-Pro-2:espn-api jasciarra$ **python3 from espn_api.football import League**
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: can't open file 'from': **[Errno 2] No such file or directory**

Jennifers-MacBook-Pro-2:espn_api jasciarra$ **from espn_api.football import League**
**from: can't read /var/mail/espn_api.football**

**Comment by cwendt94** [comment]
No problem! Okay so if you installed via Git it will only be in your relative path and not global. You will want to start the python3 cli in the top directory of espn_api folder. From there the entry point should be 
from espn_api.football import League

If this is still giving you issues you can try installing globally with pip to make sure there aren't issues with the package

**Comment by lordofthevale** [comment]
Thanks so much - got it to work!  I'm not sure what ultimately fixed it as I played around with a couple of the things you mentioned and ultimately installed with pip, ran in command line, ran python3, used the entry point you provided and it worked.  Thanks again!

**Comment by cwendt94** [comment]
Awesome, I'm glad everything is working!
