### ISSUE TITLE
Week-specific roster pull inaccurate 

### ISSUE THREAD

**Issue by davidjoshlee** [cwendt94/espn-api#97]
When using `load_roster_week(week)`, the rosters that are returned are from week 16/17 rather than the specific week. However, the stats for each player on the roster from week 16/17 are from the specified week. 

Perhaps this an ESPN API issue? Would love some more clarity!

**Comment by cwendt94** [comment]
Interesting, I will have to check what ESPN's API is returning.

To see what ESPN is returning you can create a League object in debug mode and it will log the request and response from ESPN. You should be able to see it in the console when calling load_roster_week(week).

**Comment by cwendt94** [comment]
I did some testing and `load_roster_week` is setting the correct players for the specific week. I am using a 2019 season. What season and week are you trying to view?
